"""
Known permission strings, for the dropdown suggestions on the Permissions
tab. There's no RCON command that lists every registered permission, so
this list was built by reading the installed plugins' source on the actual
server (looking for permission.RegisterPermission(...) calls, including
ones registered via a named constant rather than an inline string).

This is a snapshot as of when it was generated - if you install or remove
plugins later, ask for this list to be regenerated rather than hand-editing
it, since plugins can register more than one permission each.
"""

KNOWN_PERMISSIONS = [
    "adminhammer.allow",
    "adminradar.allowed",
    "adminradar.auto",
    "adminradar.list",
    "betterchatflood.bypass",
    "bettersay.use",
    "colouredchat.message.bypass",
    "colouredchat.message.gradient",
    "colouredchat.message.rainbow",
    "colouredchat.message.random",
    "colouredchat.message.setothers",
    "colouredchat.message.show",
    "colouredchat.message.use",
    "colouredchat.name.bypass",
    "colouredchat.name.gradient",
    "colouredchat.name.rainbow",
    "colouredchat.name.random",
    "colouredchat.name.setothers",
    "colouredchat.name.show",
    "colouredchat.name.use",
    "discordreport.admin",
    "discordreport.ignorecooldown",
    "discordreport.use",
    "freeze.frozen",
    "freeze.protect",
    "freeze.use",
    "grouplimits.ignore",
    "infiniteammo.use",
    "inventoryviewer.allowed",
    "inventoryviewer.unlock",
    "payback.admin",
    "payback3.admin",
    "payback3.user",
    "playeradministration.access.allowfreeze",
    "playeradministration.access.ban",
    "playeradministration.access.clearinventory",
    "playeradministration.access.detailedinfo",
    "playeradministration.access.heal",
    "playeradministration.access.hurt",
    "playeradministration.access.kick",
    "playeradministration.access.kill",
    "playeradministration.access.mute",
    "playeradministration.access.perms",
    "playeradministration.access.recovermetabolism",
    "playeradministration.access.resetblueprint",
    "playeradministration.access.resetmetabolism",
    "playeradministration.access.show",
    "playeradministration.access.spectate",
    "playeradministration.access.teleport",
    "playeradministration.protect.ban",
    "playeradministration.protect.hurt",
    "playeradministration.protect.kick",
    "playeradministration.protect.kill",
    "playeradministration.protect.reset",
    "rustcord.hidechat",
    "rustcord.hidejoinquit",
    "smartchatbot.messages",
    "steamchecks.skip",
    "ufilter.admin",
    "ufilter.bypass",
    "vanish.allow",
    "vanish.damage",
    "vanish.invviewer",
    "vanish.permanent",
    "vanish.teleport",
    "vanish.unlock",
    "voicemute.list",
    "voicemute.mute",
    "voicemute.unmute",
]
